### ISSUE TITLE
Meeting1

### ISSUE THREAD

**Issue by nhistory** [pacemakerIT/Gachi#1]
### Agenda

- [x] Github project 사용방법
- [x] Landing page design template 결정
- [x] #5 

### Action Items

- [x] #7 한글 폰트 적용, Header 메뉴 테스트 화요일날 결정
   - [https://www.figma.com/design/ZjWI70V0DzlIS9j7n4liqx/Comforty---eCommerce-Figma-Template-(Community)-(Community)?node-id=2610-14&t=xTV4DUj8FtZTH4J0-1](https://www.figma.com/design/ZjWI70V0DzlIS9j7n4liqx/Comforty---eCommerce-Figma-Template-(Community)-(Community)?node-id=2610-14&t=xTV4DUj8FtZTH4J0-1)
- [x] #4 리서치, 금요일 미팅에서 논의
   - React + TypeScript
   - Nextjs + MUI
   - animation: framer-animation
- [x] #2  다음주 화요일 미팅까지 완성
  - [x] #10
  - [x] #9
  - [x] #8
